### ISSUE TITLE
Possibly incorrect proton directory

### ISSUE THREAD

**Issue by Rahul-R5** [Termuellinator/Proton-Community-Updater#1]
I tried running it having no custom proton installed prior to it. It looks for `compatibilitytools.d` under `$HOME/.steam/steam/` and errors out but custom proton from GloriousEggroll is suggested to be installed in `$HOME/.steam/root/compatibilitytools.d/`

**Comment by Termuellinator** [comment]
`$HOME/.steam/steam/` and `$HOME/.steam/root/` should normally symlink to `$HOME/.local/share/steam/` as far as i know - but i guess it would maybe be better to directly target `$HOME/.local/share/Steam/compatibilitytools.d/`.  If someone manually installed steam to somewhere else, he probably is knowledgeable enough to change the `proton_dir` variable at the beginning of the script.

I wasn't sure if steam had the `compatibilitytools.d` subfolder by default - but i guess it can't really hurt to create it if it isn't found? If anyone knows possible issues in that regard, please let me know :)

Thanks for the feedback, should be fixed in 1.2.

**Comment by dubigrasu** [comment]
> `$HOME/.steam/steam/` and `$HOME/.steam/root/` should normally symlink to `$HOME/.local/share/steam/` as far as i know ...
> 
On Ubuntu 20 LTS  they link to  `$HOME/.steam/debian-installation/`.

**Comment by Termuellinator** [comment]
are you sure? i've not found anything in that regard, all ubuntu-related threads i found also state `$HOME/.local/share/Steam/` as the default? `debian-installation` sounds like it might be a pretty old system that carried that on through a lot of sys-upgrades?

**Comment by dubigrasu** [comment]
Is a fresh installation. From what I observed the steam installer from Valve is indeed using `$HOME/.local/share/Steam/` as default.
But the steam installer provided by Ubuntu repos (which I used) is defaulting to `$HOME/.steam/debian-installation/`

From `/usr/games/steam` on my system:

>     # This is a new installation, so use a distinct directory to avoid
>     # file collisions. Valve would use $XDG_DATA_HOME/Steam here.
>     # Debian uses a subdirectory of ~/.steam, to avoid having a mixture
>     # of XDG basedirs and traditional dotfiles in the same application.
>     STEAMDIR="$HOME/.steam/debian-installation"

**Comment by Termuellinator** [comment]
I've added a check if the default or the ubuntu-directory exist and use them accordingly. Could you please check if that works on your ubuntu-install before i release it?

**Comment by dubigrasu** [comment]
Yes, it does work.
